### ISSUE TITLE
About the area

### ISSUE THREAD

**Issue by ABCCBA-CYBER** [BastienBoymond/korea-concert-ticket-bot#1]
I chose area CDEF, why the program ran between A,C,D,E? Thank you for your commitment

**Comment by BastienBoymond** [comment]
Hello !

Can you send me:

The platform of the concert [melon, Yes24, Interpark]
The id of the concert
So i can try it and fix those but

**Comment by ABCCBA-CYBER** [comment]
melon 210013
thanks!

**Comment by BastienBoymond** [comment]
okey will try this soon and come to you soon

**Comment by BastienBoymond** [comment]
Hello by trying I got the excepted result

Have you do 
C,D,E,F ?
Or CDEF

Actually sometime when they got none they go on A
