### ISSUE TITLE
MelonTicket error

### ISSUE THREAD

**Issue by FranCC1216** [BastienBoymond/korea-concert-ticket-bot#3]
tkgloabl.melon.com:This event is not available for Melon Ticket Global.Please select another event；

**Comment by BastienBoymond** [comment]
hello can i have more detail please ?

**Comment by FranCC1216** [comment]
hello,ID:209989,Date:2024-08-10,Time:19:00,Sections:V1,V2

**Comment by BastienBoymond** [comment]
This problem is not from my script but from melon ticket.

I don't know why this concert is block for international person

I'm really sorry about it...
